{% set name = "mariadb" %}
{% set version = "1.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mariadb-{{ version }}.tar.gz
  sha256: 3c7eebcb94588b879069a00ae3894ef404f24ed350c40d633ccb98964bc1de55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - pip
    - python >=3.6
    - mysql-connector-c
  run:
    - python >=3.6
    - mysql-connector-c
test:
  imports:
    - mariadb
  commands:
    - pip check
  requires:
    - pip
    - {{ compiler('c') }}

about:
  home: https://www.github.com/mariadb-corporation/mariadb-connector-python
  summary: Python MariaDB extension
  license: LGPL-2.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HokiePedro
